[package]
name = "qr-code-desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.102"
env_logger = "0.11.10"
log = "0.4.29"
ply-engine = { version = "1.1", features = ["tinyvg", "text-styling"] }
qr-code-styling = "0.1.1"
rfd = "0.17.2"
strum = { version = "0.28.0", features = ["derive"] }
strum_macros = "0.28.0"
